networks:
  default: celo_mainnet
  development:
    cmd_settings:
      default_balance: "10000000 ether"
  live:
    settings:
    gas_limit: "auto"
    gas_price: "auto"


dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - OpenZeppelin/openzeppelin-contracts@3.2.0
  - ubeswap/ubeswap@mainnet-v1
