networks:
  development:
    cmd_settings:
      default_balance: "10000000 ether"
  live:
    gas_limit: 10000000

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - OpenZeppelin/openzeppelin-contracts@3.2.0
